# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MainUser\Documents\GitHub\Sema\school_update\sign\main_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setStyleSheet("background-color:qconicalgradient(cx:0, cy:0, angle:135, stop:0.129353 rgba(27, 27, 141, 255), stop:0.375 rgba(0, 0, 127, 69), stop:0.412935 rgba(107, 107, 178, 255), stop:0.423533 rgba(148, 148, 201, 145), stop:0.457711 rgba(74, 74, 163, 255), stop:0.518717 rgba(153, 153, 230, 255), stop:0.55 rgba(144, 144, 199, 255), stop:0.57754 rgba(117, 117, 182, 255), stop:0.625 rgba(108, 108, 181, 255), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(600, 500))
        self.frame.setMaximumSize(QtCore.QSize(681, 498))
        self.frame.setSizeIncrement(QtCore.QSize(600, 500))
        self.frame.setStyleSheet("background-color:transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.login_Button = QtWidgets.QPushButton(self.frame)
        self.login_Button.setGeometry(QtCore.QRect(303, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_Button.setFont(font)
        self.login_Button.setStyleSheet("background-color:rgb(255, 255, 255) ;\n"
"border-radius:10px;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.login_Button.setObjectName("login_Button")
        self.signup_Button = QtWidgets.QPushButton(self.frame)
        self.signup_Button.setGeometry(QtCore.QRect(440, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.signup_Button.setFont(font)
        self.signup_Button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"color: rgb(0, 0, 0);")
        self.signup_Button.setObjectName("signup_Button")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 50, 591, 91))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_Button.setText(_translate("MainWindow", "LOGIN"))
        self.signup_Button.setText(_translate("MainWindow", "SIGNUP"))
        self.label.setText(_translate("MainWindow", "SCHOOL INFO"))

