# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/onur/Documents/GitHub/school_update/Chat_UI/chat_mobil.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 690)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 431, 671))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.ongoing_messages_widget = QtWidgets.QWidget(self.page)
        self.ongoing_messages_widget.setGeometry(QtCore.QRect(0, 0, 431, 671))
        self.ongoing_messages_widget.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set the background color */\n"
"    border-radius: 10px; /* Set the border radius */ shadow */\n"
"}")
        self.ongoing_messages_widget.setObjectName("ongoing_messages_widget")
        self.messageListWidget = QtWidgets.QListWidget(self.ongoing_messages_widget)
        self.messageListWidget.setGeometry(QtCore.QRect(20, 170, 391, 481))
        self.messageListWidget.setStyleSheet("QListWidget {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    border: 1px solid #e0e0e0; /* Border for better visibility */\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.messageListWidget.setObjectName("messageListWidget")
        self.user_search = QtWidgets.QLineEdit(self.ongoing_messages_widget)
        self.user_search.setGeometry(QtCore.QRect(20, 90, 391, 41))
        self.user_search.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    border: 1px solid #e0e0e0;\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.user_search.setClearButtonEnabled(False)
        self.user_search.setObjectName("user_search")
        self.active_message_label_3 = QtWidgets.QLabel(self.ongoing_messages_widget)
        self.active_message_label_3.setGeometry(QtCore.QRect(20, 140, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(True)
        self.active_message_label_3.setFont(font)
        self.active_message_label_3.setStyleSheet("QLabel {\n"
"    color: darkgray;  /* Dark Gray using color name */\n"
"}")
        self.active_message_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.active_message_label_3.setObjectName("active_message_label_3")
        self.widget = QtWidgets.QWidget(self.ongoing_messages_widget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 381, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.current_user_avatar_label = QtWidgets.QLabel(self.widget)
        self.current_user_avatar_label.setStyleSheet("")
        self.current_user_avatar_label.setObjectName("current_user_avatar_label")
        self.verticalLayout_2.addWidget(self.current_user_avatar_label)
        self.profile_name_label = QtWidgets.QLabel(self.widget)
        self.profile_name_label.setObjectName("profile_name_label")
        self.verticalLayout_2.addWidget(self.profile_name_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.active_message_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.active_message_label.setFont(font)
        self.active_message_label.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set the background color */\n"
"    border-radius: 10px; /* Set the border radius */\n"
"}")
        self.active_message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.active_message_label.setObjectName("active_message_label")
        self.horizontalLayout_2.addWidget(self.active_message_label)
        self.redirect_create_group_button = QtWidgets.QPushButton(self.widget)
        self.redirect_create_group_button.setStyleSheet("QPushButton {\n"
"    background-color: #4fa3d1; /* Darker blue background */\n"
"    border: 1px solid #5e92b8; /* Slightly darker border color */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 5px 10px; /* Adjust padding if needed */\n"
"    color: #ffffff; /* Text color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3d81af; /* Change background color on hover */\n"
"    border: 1px solid #4c748e; /* Change border color on hover */\n"
"}")
        self.redirect_create_group_button.setObjectName("redirect_create_group_button")
        self.horizontalLayout_2.addWidget(self.redirect_create_group_button)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.specific_message_widget = QtWidgets.QWidget(self.page_2)
        self.specific_message_widget.setGeometry(QtCore.QRect(0, 0, 431, 911))
        self.specific_message_widget.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set the background color */\n"
"    border-radius: 10px; /* Set the border radius */ shadow */\n"
"}")
        self.specific_message_widget.setObjectName("specific_message_widget")
        self.selectedMessageList = QtWidgets.QListWidget(self.specific_message_widget)
        self.selectedMessageList.setGeometry(QtCore.QRect(10, 80, 411, 521))
        self.selectedMessageList.setMouseTracking(False)
        self.selectedMessageList.setStyleSheet("QListWidget {\n"
"    background-image: url(\"files/background.png\");\n"
"    background-position: center center; \n"
"}")
        self.selectedMessageList.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.selectedMessageList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectedMessageList.setObjectName("selectedMessageList")
        self.message_text_field = QtWidgets.QTextEdit(self.specific_message_widget)
        self.message_text_field.setGeometry(QtCore.QRect(10, 610, 341, 51))
        self.message_text_field.setStyleSheet("QTextEdit {\n"
"    background-color: #ffffff; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    border: 1px solid #d0d0d0; /* Border for better visibility */\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.message_text_field.setObjectName("message_text_field")
        self.send_message_button = QtWidgets.QPushButton(self.specific_message_widget)
        self.send_message_button.setGeometry(QtCore.QRect(360, 610, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.send_message_button.setFont(font)
        self.send_message_button.setStyleSheet("QPushButton {\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"   icon-size: 30px;\n"
"}\n"
"")
        self.send_message_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/onur/Documents/GitHub/school_update/Chat_UI/../../../../Downloads/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_message_button.setIcon(icon)
        self.send_message_button.setIconSize(QtCore.QSize(40, 40))
        self.send_message_button.setObjectName("send_message_button")
        self.layoutWidget = QtWidgets.QWidget(self.specific_message_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 10, 275, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.specific_avatar_label = QtWidgets.QLabel(self.layoutWidget)
        self.specific_avatar_label.setObjectName("specific_avatar_label")
        self.horizontalLayout.addWidget(self.specific_avatar_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.specific_username_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.specific_username_label.setFont(font)
        self.specific_username_label.setObjectName("specific_username_label")
        self.verticalLayout.addWidget(self.specific_username_label)
        self.specific_status_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(19)
        font.setItalic(True)
        self.specific_status_label.setFont(font)
        self.specific_status_label.setObjectName("specific_status_label")
        self.verticalLayout.addWidget(self.specific_status_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.back_button2 = QtWidgets.QPushButton(self.specific_message_widget)
        self.back_button2.setGeometry(QtCore.QRect(20, 10, 41, 32))
        self.back_button2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/onur/Documents/GitHub/school_update/Chat_UI/../../../../Downloads/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button2.setIcon(icon1)
        self.back_button2.setIconSize(QtCore.QSize(32, 32))
        self.back_button2.setObjectName("back_button2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.ongoing_messages_widget_2 = QtWidgets.QWidget(self.page_3)
        self.ongoing_messages_widget_2.setGeometry(QtCore.QRect(0, 0, 431, 671))
        self.ongoing_messages_widget_2.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set the background color */\n"
"    border-radius: 10px; /* Set the border radius */\n"
"}")
        self.ongoing_messages_widget_2.setObjectName("ongoing_messages_widget_2")
        self.select_group_members_list = QtWidgets.QListWidget(self.ongoing_messages_widget_2)
        self.select_group_members_list.setGeometry(QtCore.QRect(20, 170, 391, 471))
        self.select_group_members_list.setStyleSheet("QListWidget {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    spacing: 2px;\n"
"    border: 1px solid #e0e0e0; /* Border for better visibility */\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.select_group_members_list.setUniformItemSizes(False)
        self.select_group_members_list.setObjectName("select_group_members_list")
        self.active_message_label_2 = QtWidgets.QLabel(self.ongoing_messages_widget_2)
        self.active_message_label_2.setGeometry(QtCore.QRect(10, 10, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.active_message_label_2.setFont(font)
        self.active_message_label_2.setStyleSheet("QWidget {\n"
"    background-color: #ffffff; /* Set the background color */\n"
"    border-radius: 10px; /* Set the border radius */\n"
"}")
        self.active_message_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.active_message_label_2.setObjectName("active_message_label_2")
        self.user_search_for_group_label = QtWidgets.QLineEdit(self.ongoing_messages_widget_2)
        self.user_search_for_group_label.setGeometry(QtCore.QRect(20, 110, 271, 41))
        self.user_search_for_group_label.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    border: 1px solid #e0e0e0;\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.user_search_for_group_label.setClearButtonEnabled(False)
        self.user_search_for_group_label.setObjectName("user_search_for_group_label")
        self.create_group_button = QtWidgets.QPushButton(self.ongoing_messages_widget_2)
        self.create_group_button.setGeometry(QtCore.QRect(300, 110, 113, 41))
        self.create_group_button.setStyleSheet("QPushButton {\n"
"    background-color: #4fa3d1; /* Darker blue background */\n"
"    border: 1px solid #5e92b8; /* Slightly darker border color */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 5px 10px; /* Adjust padding if needed */\n"
"    color: #ffffff; /* Text color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3d81af; /* Change background color on hover */\n"
"    border: 1px solid #4c748e; /* Change border color on hover */\n"
"}")
        self.create_group_button.setObjectName("create_group_button")
        self.group_name_label = QtWidgets.QLineEdit(self.ongoing_messages_widget_2)
        self.group_name_label.setGeometry(QtCore.QRect(20, 60, 391, 41))
        self.group_name_label.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Set the border radius */\n"
"    padding: 2px; /* Adjust padding if needed */\n"
"    border: 1px solid #e0e0e0;\n"
"    outline: none; /* Remove the outline */\n"
"}")
        self.group_name_label.setClearButtonEnabled(False)
        self.group_name_label.setObjectName("group_name_label")
        self.back_button_2 = QtWidgets.QPushButton(self.ongoing_messages_widget_2)
        self.back_button_2.setGeometry(QtCore.QRect(20, 10, 41, 32))
        self.back_button_2.setText("")
        self.back_button_2.setIcon(icon1)
        self.back_button_2.setIconSize(QtCore.QSize(32, 32))
        self.back_button_2.setObjectName("back_button_2")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat Window"))
        self.user_search.setPlaceholderText(_translate("MainWindow", "Search People"))
        self.active_message_label_3.setText(_translate("MainWindow", "Your Active Messages"))
        self.current_user_avatar_label.setText(_translate("MainWindow", "Avatar"))
        self.profile_name_label.setText(_translate("MainWindow", "TextLabel"))
        self.active_message_label.setText(_translate("MainWindow", "Chatty"))
        self.redirect_create_group_button.setText(_translate("MainWindow", "Create Group"))
        self.specific_avatar_label.setText(_translate("MainWindow", "Avatar"))
        self.specific_username_label.setText(_translate("MainWindow", "User or Group Name"))
        self.specific_status_label.setText(_translate("MainWindow", "Status"))
        self.active_message_label_2.setText(_translate("MainWindow", "Create Group"))
        self.user_search_for_group_label.setPlaceholderText(_translate("MainWindow", "Search People"))
        self.create_group_button.setText(_translate("MainWindow", "Create Group"))
        self.group_name_label.setPlaceholderText(_translate("MainWindow", "Group Name"))
