# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/onur/Documents/GitHub/school_update/Chat_UI/MessageItemWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 69)
        self.avatar_label = QtWidgets.QLabel(Form)
        self.avatar_label.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.avatar_label.setText("")
        self.avatar_label.setPixmap(QtGui.QPixmap("/Users/onur/Documents/GitHub/school_update/Chat_UI/../../../../Downloads/7163d1636161a58fc386906ba3b6100a.webp"))
        self.avatar_label.setScaledContents(True)
        self.avatar_label.setObjectName("avatar_label")
        self.person_label = QtWidgets.QLabel(Form)
        self.person_label.setGeometry(QtCore.QRect(70, 10, 60, 16))
        self.person_label.setObjectName("person_label")
        self.message_preview_label = QtWidgets.QLabel(Form)
        self.message_preview_label.setGeometry(QtCore.QRect(70, 30, 180, 16))
        self.message_preview_label.setMinimumSize(QtCore.QSize(180, 0))
        self.message_preview_label.setObjectName("message_preview_label")
        self.date_time_label = QtWidgets.QLabel(Form)
        self.date_time_label.setGeometry(QtCore.QRect(210, 10, 60, 16))
        self.date_time_label.setObjectName("date_time_label")
        self.unread_count = QtWidgets.QLabel(Form)
        self.unread_count.setGeometry(QtCore.QRect(249, 30, 21, 20))
        self.unread_count.setObjectName("unread_count")
        self.message_preview_label.setBuddy(self.message_preview_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.person_label.setText(_translate("Form", "TextLabel"))
        self.message_preview_label.setText(_translate("Form", "TextLabel"))
        self.date_time_label.setText(_translate("Form", "TextLabel"))
        self.unread_count.setText(_translate("Form", "2"))
